import {useEffect,useRef,useState,type FormEvent} from 'react';
import { ArrowLeft, ArrowRight, Cloud, LockKeyhole, Mail, UserRound, X } from 'lucide-react';
import type { MomentoStore } from '../hooks/useMomento';
import { trackEvent } from '../lib/analytics';

type Tab='login'|'register'|'profile';
export default function AccountDialog({store,onClose}:{store:MomentoStore,onClose:()=>void}) {
  const [tab,setTab]=useState<Tab>(store.user?'profile':'login');
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState(store.profile.display_name);
  const [bio,setBio]=useState(store.profile.bio);
  const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const [progress,setProgress]=useState('');
  const closeRef=useRef<HTMLButtonElement>(null);
  useEffect(()=>closeRef.current?.focus(),[]);
  useEffect(()=>{if(store.user){setTab('profile');setName(store.profile.display_name);setBio(store.profile.bio);}},[store.user,store.profile.display_name,store.profile.bio]);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');
    try{if(tab==='register'){const result=await store.signUp(email,password,name.trim());setMessage(result.confirmEmail?'Check your email to confirm your account, then sign in.':'Account created. Your journal is ready.');if(result.confirmEmail)setTab('login');}
    else if(tab==='login'){await store.signIn(email,password);setMessage('Signed in. Your private journal is loading.');}
    else {await store.updateProfile({display_name:name.trim(),bio:bio.trim()});setMessage('Your profile has been updated.');}}
    catch(e){setMessage(e instanceof Error?e.message:'Something went wrong.');}finally{setBusy(false);}}
  async function doImport(){setBusy(true);setMessage('');try{const n=await store.importDrafts((done,total)=>setProgress(`IMPORTING ${done} / ${total}`));setMessage(`${n} ${n===1?'memory':'memories'} imported. They are now in your cloud journal.`);setProgress('');}catch(e){setMessage(e instanceof Error?e.message:'Import interrupted. Already imported memories will not be duplicated.');}finally{setBusy(false);}}
  return <div className="product-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className="account-dialog paper-surface" role="dialog" aria-modal="true" aria-label="MOMENTO account"><header className="product-top"><span className="mini-overline">✳ &nbsp; MOMENTO / YOUR LITTLE CORNER</span><button ref={closeRef} className="product-close" aria-label="Close account" onClick={onClose}><X size={21}/></button></header><div className="account-columns"><div className="account-illustration"><img src="/keepsake-terrace.webp" alt="Illustrated suitcase of memories on a Mediterranean terrace"/><div className="account-illustration-copy"><span>COLLECTED WITH CARE</span><h2>A little home<br/>for <em>everything.</em></h2><p>The stories are yours, wherever you go.</p></div></div><div className="account-content">{!store.cloudEnabled&&<div className="account-unconfigured"><LockKeyhole size={22}/><strong>Cloud setup needed.</strong><p>The journal works in guest mode now. To enable real accounts and synchronization, connect your own Supabase project using the README setup guide.</p></div>}
        {store.user&&tab==='profile'?<><span className="eyebrow">WELCOME BACK ✳</span><h2>Your little <em>profile.</em></h2><p className="account-intro">Signed in as {store.user.email}</p><form className="account-form" onSubmit={e=>void submit(e)}><label>DISPLAY NAME<input maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="What should we call you?"/></label><label>A LITTLE ABOUT YOU<textarea maxLength={240} rows={3} value={bio} onChange={e=>setBio(e.target.value)} placeholder="The stories I like to keep..."/></label><button className="black-pill" disabled={busy}>SAVE PROFILE <ArrowRight size={15}/></button></form>{store.drafts.length>0&&<div className="account-import"><Cloud size={23}/><strong>{store.drafts.length} memories on this device</strong><p>Move these guest memories into your private cloud account, including their photographs.</p><button disabled={busy} onClick={()=>void doImport()}>{progress||'IMPORT MY MEMORIES →'}</button></div>}<button className="account-back" onClick={async()=>{setBusy(true);try{await store.signOut();onClose();}catch(e){setMessage(e instanceof Error?e.message:'Could not sign out.');}finally{setBusy(false);}}}>SIGN OUT <ArrowRight size={14}/></button></>
        :<><span className="eyebrow">YOUR MEMORIES, ANYWHERE</span><h2>{tab==='register'?'Begin your':'Welcome'}<br/><em>{tab==='register'?'own story.':'back.'}</em></h2><p className="account-intro">{tab==='register'?'Make a free account to keep your moments in sync.':'Sign in to find the moments you saved.'}</p><div className="auth-tabs"><button className={tab==='login'?'selected':''} onClick={()=>{setTab('login');setMessage('');}}>LOG IN</button><button className={tab==='register'?'selected':''} onClick={()=>{if(tab!=='register')trackEvent('signup_started',{source:'account'});setTab('register');setMessage('');}}>CREATE ACCOUNT</button></div><form className="account-form" onSubmit={e=>void submit(e)}>{tab==='register'&&<label>YOUR NAME<div className="input-icon"><UserRound size={17}/><input required maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></div></label>}<label>EMAIL<div className="input-icon"><Mail size={17}/><input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></div></label><label>PASSWORD<div className="input-icon"><LockKeyhole size={17}/><input type="password" required minLength={8} autoComplete={tab==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/></div></label><button className="black-pill" disabled={!store.cloudEnabled||busy}>{busy?'PLEASE WAIT...':tab==='register'?'CREATE MY ACCOUNT':'LOG IN'} <ArrowRight size={15}/></button></form><p className="account-privacy">Your memories are private by default. Only you can access your cloud journal.</p><button className="account-back" onClick={onClose}><ArrowLeft size={14}/> CONTINUE WITHOUT AN ACCOUNT</button></>}
        {message&&<div className="account-message" role="status">{message}</div>}
      </div></div></section></div>;
}
